prev_close = DELAY($adj_close, 1)
gap = DIVIDE(SUBTRACT($adj_open, prev_close), prev_close)
gap_up = IF_THEN_ELSE(GT(gap, 0), gap, 0)
gap_dn = IF_THEN_ELSE(LT(gap, 0), ABS(gap), 0)
up_streak = TS_STREAK(GT(gap, 0))
dn_streak = TS_STREAK(LT(gap, 0))
up_weighted = MULTIPLY(CAST(up_streak, 'float'), gap_up)
dn_weighted = MULTIPLY(CAST(dn_streak, 'float'), gap_dn)
streak_net = SUBTRACT(up_weighted, dn_weighted)
streak_rank = RANK(streak_net)
streak_rank_ema3 = EMA(streak_rank, 3)
CS_NEUTRALIZE(streak_rank_ema3, CS_BUCKET(LOG($float_cap), 3))
