kg = CS_ZSCORE(KLINE_GEOMETRY($open, $high, $low, $close, 20))
vd = DIVIDE(SUBTRACT($close, $vwap), $vwap)
rev = NEG(CS_ZSCORE(TS_MEAN(vd, 20)))
mom120 = TS_MEAN($ret, 120)
mom20 = TS_MEAN($ret, 20)
mom = CS_ZSCORE(SUBTRACT(mom120, mom20))
wkt = CS_ZSCORE(TS_TREND_RANK($adj_close@1w, 13))
raw = ADD(ADD(ADD(NEG(kg), rev), MULTIPLY(mom, 0.5)), MULTIPLY(wkt, 0.5))
CS_WINSORIZE(raw, 0.02, 0.98)
