np_z = CS_ZSCORE(CS_WINSORIZE($funda_netprofit_yoy, 0.01, 0.99))
vol_z = CS_ZSCORE(TS_STD($ret, 20))
amt = TS_MEAN($amount, 20)
turnover_z = CS_ZSCORE(DIVIDE(amt, $float_cap))
np_center = EXP(MULTIPLY(np_z, MULTIPLY(np_z, -0.5)))
vol_center = EXP(MULTIPLY(vol_z, MULTIPLY(vol_z, -0.5)))
to_center = EXP(MULTIPLY(turnover_z, MULTIPLY(turnover_z, -0.5)))
score = ADD(ADD(np_center, vol_center), to_center)
CS_NEUTRALIZE(CS_WINSORIZE(score, 0.01, 0.99), CS_BUCKET(LOG($float_cap), 10))
