ocr = DIVIDE(SUBTRACT($close, $open), $open)
o_skw = TS_SKEW(ocr, 90)
wk_amp13 = SUBTRACT(TS_MAX($adj_close@1w, 13), TS_MIN($adj_close@1w, 13))
vol20 = TS_STD($ret, 20)
sk_z = CS_ZSCORE(NEG(o_skw))
amp_z = CS_ZSCORE(NEG(wk_amp13))
vol_z = CS_ZSCORE(NEG(vol20))
sig = ADD(MULTIPLY(sk_z, 4), ADD(amp_z, vol_z))
RANK(CS_NEUTRALIZE(CS_WINSORIZE(sig, 0.01, 0.99), CS_BUCKET(LOG($float_cap), 10)))
