hlr = DIVIDE($high, $low)
hl_l = LOG(hlr)
park20 = TS_STD(hl_l, 20)
park_z = TS_ZSCORE(park20, 180)
intraday_r = SUBTRACT(LOG($adj_close), LOG($open))
overnight_r = SUBTRACT(LOG($open), LOG(DELAY($adj_close, 1)))
iv = TS_STD(intraday_r, 20)
ov = TS_STD(overnight_r, 20)
share = DIVIDE(iv, ADD(iv, ov))
combo = ADD(NEG(RANK(park_z)), MULTIPLY(RANK(share), 0.5))
CS_NEUTRALIZE(CS_ZSCORE(combo), CS_BUCKET(LOG($float_cap), 10))
