lev = DIVIDE($funda_fs_total_assets, $funda_fs_total_equity)
lev_win = CS_WINSORIZE(lev, 0.01, 0.99)
lev_z = CS_ZSCORE(lev_win)
lev_ind = CS_NEUTRALIZE(lev_z, $industry_sw_l1)
lev_size = CS_NEUTRALIZE(lev_ind, CS_BUCKET(LOG($float_cap), 10))
roe_win = CS_WINSORIZE($funda_roe, 0.01, 0.99)
roe_z = CS_ZSCORE(roe_win)
roe_ind = CS_NEUTRALIZE(roe_z, $industry_sw_l1)
roe_size = CS_NEUTRALIZE(roe_ind, CS_BUCKET(LOG($float_cap), 10))
yoy_win = CS_WINSORIZE($funda_netprofit_yoy, 0.01, 0.99)
yoy_z = CS_ZSCORE(yoy_win)
yoy_ind = CS_NEUTRALIZE(yoy_z, $industry_sw_l1)
yoy_size = CS_NEUTRALIZE(yoy_ind, CS_BUCKET(LOG($float_cap), 10))
quality = RANK(roe_size) + RANK(yoy_size) - RANK(lev_size)
quality
