wk_ret = TS_PCTCHANGE($adj_close@1w, 1)
wk_ac = TS_CORR(wk_ret, DELAY(wk_ret, 1), 13)
wk_sk = NEG(TS_SKEW(wk_ret, 13))
wk_range = SUBTRACT($high@1w, $low@1w)
wk_amp = NEG(SLOPE(wk_range, 10))
wk_er = TS_EFFICIENCY_RATIO($adj_close@1w, 13)
wk_lw = TS_MEAN(DIVIDE(SUBTRACT($close@1w, $low@1w), SUBTRACT($high@1w, $low@1w)), 13)
f = ADD(FILLNA(RANK(wk_ac), 0.5), ADD(MULTIPLY(FILLNA(RANK(wk_sk), 0.5), 0.5), ADD(MULTIPLY(FILLNA(RANK(wk_amp), 0.5), 0.5), ADD(MULTIPLY(FILLNA(RANK(wk_er), 0.5), 0.3), MULTIPLY(FILLNA(RANK(wk_lw), 0.5), 0.3)))))
CS_NEUTRALIZE(RANK(f), CS_BUCKET(LOG($float_cap), 10))
