wk_rng = SUBTRACT($high@1w, $low@1w)
wk_sq = NEG(DIVIDE(TS_MEAN(wk_rng, 6), TS_MEAN(wk_rng, 24)))
wk_geo = NEG(KLINE_GEOMETRY($open@1w, $high@1w, $low@1w, $close@1w, 26))
wk_st = DIVIDE(SUBTRACT($close@1w, TS_MIN($low@1w, 39)), SUBTRACT(TS_MAX($high@1w, 39), TS_MIN($low@1w, 39)))
raw = ADD(ADD(CS_ZSCORE(wk_sq), CS_ZSCORE(wk_geo)), CS_ZSCORE(wk_st))
CS_NEUTRALIZE(raw, CS_BUCKET(LOG($float_cap), 10))
